language: python

cache: pip

python:
- 3.6
- nightly

# We don't want travis to fail if a new experimental feature breaks us
jobs:
    allow_failures:
        - python: nightly
    fast_finish: true

install:
  # Update apt-get and install GSL
  - sudo apt-get update
  - sudo apt-get install libgsl0-dev swig3.0 libfftw3-dev gobject-introspection python-gobject gfortran libmpfr-dev libhdf5-dev liblapack-dev libnlopt-dev libcfitsio3-dev gir1.2-glib-2.0 libgirepository1.0-dev python3-gi python-gi -y

  # Install the dependencies
  - git clone https://github.com/LSSTDESC/CCL ; cd CCL ; python setup.py install ; cd -
  - pip install pycairo==1.19.1
  - pip install pygobject
  - export MPLBACKEND="agg"
  - pip install matplotlib
  - pip install -r requirements.txt

  #- export GI_TYPELIB_PATH="${GI_TYPELIB_PATH}:/usr/share/gir-1.0"
  
  # Install the package
  - python setup.py install

  # Install dependencies required to test the docs
  - sudo apt-get install pandoc -y
  - pip install ipykernel
  - python -m ipykernel install --user --name python3 --display-name python3
  - pip install sphinx==2.1.2 sphinx_rtd_theme nbconvert jupyter_client

  # Install coveralls for test coverage
  - pip install coveralls pytest-cov

script:
  # Run the unit tests:
  - py.test tests/ #--ignore=cluster_toolkit/tests --cov=clmm/

  # Run the docs:
  #- make -C docs/ html

after_success:
  - coveralls
