[tool.black]
line-length  = 100

[tool.pylint]
max-line-length = 100
disable = ["R0913"]
good-names = ["ra", "z", "z1", "z2", "a", "a1", "a2",
              "gt", "gx", "mu", "da", "i",
              "H0", "Omega_b0", "Omega_dm0", "Omega_k0",
              "h", "Omega_m", "Omega_b",
              "get_Omega_m", "get_E2", "get_E2Omega_m", 
              "_get_Omega_m", "_get_E2", "_get_E2Omega_m", 
              ]
max-public-methods = 30
ignored-modules = ["scipy.special"]

[tool.pylint.'DESIGN']
max-locals = 20
max-args = 20
