outpath: temp
matching_mode: membership # Options: proximity, membership

cosmology:
    backend: Astropy # Options are Astropy, CCL.
    parameters:
        H0: 70.0
        Omega_b0: 0.05
        Omega_dm0: 0.25
        Omega_k0: 0.0

catalog1:
    file: cat1.fits
    name: catalog 1
    columns:
        id: ID # Required if matching by members
        ra: RA
        dec: DEC
        z: Z
        mass: MASS
        radius: RADIUS_ARCMIN
    radius_unit: ARCMIN # Options: radians, degrees, arcmin, arcsec, pc, kpc, Mpc, M200b, M200c, M##b/c...
    labels: # Labels for plots. If not availble, column_{name} used.
        mass: Mass1
    footprint: # Footprint information. Used to create artificial footprint and on recovery rate.
        file: ftpt1.fits
        nside: 4096 # healpix NSIDE.
        nest: False # healpix nested ordering. if false use ring.
        pixel: pixel # Name of pixel column of footprint.
        detfrac: None # Name of detfrac column of footprint. Use 'None' if not existing.
        zmax: None # Name of zmax column of footprint. Use 'None' if not existing.
    members: # Members of catalog, only required for membership matching
        file: cat1_mem.fits
        name: members 1
        columns: # MUST include at least id_cluster
            id: ID # Required if matching the members by id
            id_cluster: ID_CLUSTER
            ra: RA # Required if matching the members by angular proximity
            dec: DEC # Required if matching the members by angular proximity
            z: Z # Required if matching the members by angular proximity with physical distance parameter
        labels: # Labels for plots. If not availble, column_{name} used.
            id: members id

catalog2:
    file: cat2.fits
    name: catalog 2
    columns:
        id: ID # Required if matching by members
        ra: RA
        dec: DEC
        z: Z
        mass: MASS
        radius: RADIUS_ARCMIN
    radius_unit: ARCMIN # Options: radians, degrees, arcmin, arcsec, pc, kpc, Mpc, M200b, M200c, M##b/c...
    labels: # Labels for plots. If not availble, column_{name} used.
        mass: Mass2
    footprint: # Footprint information. Used to create artificial footprint and on recovery rate.
        file: ftpt2.fits
        nside: 4096 # healpix NSIDE.
        nest: False # healpix nested ordering. if false use ring.
        pixel: pixel # Name of pixel column of footprint.
        detfrac: None # Name of detfrac column of footprint. Use 'None' if not existing.
        zmax: None # Name of zmax column of footprint. Use 'None' if not existing.
    members: # Members of catalog, only required for membership matching
        file: cat2_mem.fits
        name: members 2
        columns: # MUST include at least id_cluster
            id: ID # Required if matching the members by id
            id_cluster: ID_CLUSTER
            ra: RA # Required if matching the members by angular proximity
            dec: DEC # Required if matching the members by angular proximity
            z: Z # Required if matching the members by angular proximity with physical distance parameter
        labels: # Labels for plots. If not availble, column_{name} used.
            id: members id

proximity_match:
    type: cross # options are cross, cat1, cat2.
    verbose: True # print matching info of all clusters to screen
    step1: # Add more steps with the same keys below if required
        which_radius: max # Case of radius to be used, can be: cat1, cat2, min, max.
        preference: more_massive # options are more_massive, angular_proximity or redshift_proximity.
        catalog1:
            delta_z: .2 # Defines the zmin, zmax for matching. Options are:
                        #  'cat': uses redshift properties of the catalog.
                        #  'spline.filename': interpolates data in 'filename' (z, zmin, zmax) fmt.
                        #  float: uses delta_z*(1+z).
                        #  None: does not use z.
            match_radius: 1 arcmin # Radius for matching. If 'cat' uses the radius in the catalog, else must be in format 'value unit'.
        catalog2:
            delta_z: .2 # Defines the zmin, zmax for matching. Options are:
                        #  'cat': uses redshift properties of the catalog.
                        #  'spline.filename': interpolates data in 'filename' (z, zmin, zmax) fmt.
                        #  float: uses delta_z*(1+z).
                        #  None: does not use z.
            match_radius: 1 mpc # Radius for matching. If 'cat' uses the radius in the catalog, else must be in format 'value unit'.

membership_match:
    type: cross # options are cross, cat1, cat2.
    verbose: True # print matching info of all clusters to screen
    preference: shared_member_fraction # Options: more_massive, angular_proximity, redshift_proximity, shared_member_fraction.
    minimum_share_fraction: 0 # Minimum share fraction to consider in matches.
    match_members: True # Match the members catalogs.
    match_members_kwargs: # Arguments to match members, needed if match_members=True.
        method: id # Method for matching. Options are id or angular_distance.
        radius: None # For method=angular_distance. Radius for matching, with format 'value unit' - used fixed value (ex: 1 arcsec, 1 Mpc).
    match_members_save: True # saves file with matched members.
    match_members_load: False # load matched members, if True skips matching (and save) of members.
    match_members_file: temp_mems_mt.txt # file to save matching of members, needed if match_members_save or match_members_load is True.
    shared_members_fill: True # Adds shared members information to catalogs.
    shared_members_save: True # saves files with shared members.
    shared_members_load: False # load files with shared members, if True skips matching (and save) of members and fill (and save) of shared members.
    shared_members_file: temp_shared # Prefix of file names to save shared members, needed if shared_members_save or shared_members_load is True.

masks: # Config to be used by make_masks and recovery rate.
    catalog1:
        in_footprint1: # Flag if cluster is inside footprint.
            which_footprint: self # which footprint to use for computaions. Options: self, other.
            name: self # Name for column.
        in_footprint2: # Flag if cluster is inside footprint.
            which_footprint: other # which footprint to use for computaions. Options: self, other.
            name: other # Name for column. It will receive a ft_ prefix.
        coverfraction: # Many coverfractions can be computed by adding more "coverfraction" sections with any suffixes.
            name: other_1arcsec # Name for coverfraction column. It will receive a cf_ prefix.
            which_footprint: other # which footprint to use for computaions. Options: self, other.
            aperture: 1 arcsec # Size of aperture with units.
            window_function: nfw2D # Window to weight the coverfraction. Options are flat, nfw2D.
        coverfraction_: # Like this one.
            name: other_1arcmin # Name for coverfraction column. It will receive a cf_ prefix.
            which_footprint: other # which footprint to use for computaions. Options: self, other.
            aperture: 1 arcmin # Size of aperture with units.
            window_function: nfw2D # Window to weight the coverfraction. Options are flat, nfw2D.
    catalog2:
        in_footprint1: # Flag if cluster is inside footprint.
            which_footprint: self # which footprint to use for computaions. Options: self, other.
            name: self # Name for column.
        in_footprint2: # Flag if cluster is inside footprint.
            which_footprint: other # which footprint to use for computaions. Options: self, other.
            name: other # Name for column. It will receive a ft_ prefix.
        coverfraction: # Many coverfractions can be computed by adding more "coverfraction" sections with any suffixes.
            name: other_1arcsec # Name for coverfraction column. It will receive a cf_ prefix.
            which_footprint: other # which footprint to use for computaions. Options: self, other.
            aperture: 1 arcmin # Size of aperture with units.
            window_function: nfw2D # Window to weight the coverfraction. Options are flat, nfw2D.

mt_metrics_recovery: # Recovery rate.

    figsize: 20 20 # Figure size of figures in cm.
    dpi: 150 # The resolution in dots per inch.
    plot_case: all # Types of plots to be done. Options are simple, panel, 2D or all.
    matching_type: cross # options are cross, cat1, cat2, multi_cat1, multi_cat2, multi_join.
    line_type: steps # line, steps.
    add_mass_label: True # Add labels and legends of mass bins.
    add_redshift_label: True # Add labels and legends of redshift bins.
    add_cb: True # Add color bar in color plots.

    catalog1:
        log_mass: True
        mass_num_fmt: .2f # Format the values of mass binedges (ex: '.2f') in label.
        redshift_num_fmt: .1f # Format the values of redshift binedges (ex: '.2f') in label.
        recovery_label: None
        mass_bins: 4 # Mass bins. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        redshift_bins: 10 # Redshift bins. Can be number of bins, or (xmin, xmax, dx).
        mass_lim: None # Mass limits in plots. Must be 2 numbers (min, max) or None.
        redshift_lim: None # Redshift limits in plots. Must be 2 numbers (min, max) or None.
        recovery_lim: None # Recovery rate limits in plots. Must be 2 numbers (min, max) or None.

        masks: # Mask objects used in the computation of recovery rates. Names must correspond to those in the main "masks" section.
            case: Unmatched # Which clusters to mask on recovery rate computations. Options: None, All, Unmatched.
            in_footprint1: # Flag if cluster is inside footprint.
                name: self # Name for column.
                use: True # Use this mask.
            in_footprint2: # Flag if cluster is inside footprint.
                name: other # Name for column. It will receive a ft_ prefix.
                use: True # Use this mask.
            coverfraction: # Many coverfractions can be computed by adding more "coverfraction" sections with any suffixes.
                name: other_1arcsec # Name for coverfraction column. It will receive a cf_ prefix.
                min: 0.1 # Minimum value of cover fraction to be considered.
            coverfraction_: # Like this one.
                name: other_1arcmin # Name for coverfraction column. It will receive a cf_ prefix.
                min: 0.1 # Minimum value of cover fraction to be considered.

    catalog2:
        log_mass: True
        mass_num_fmt: .2f # Format the values of mass binedges (ex: '.2f') in label.
        redshift_num_fmt: .1f # Format the values of redshift binedges (ex: '.2f') in label.
        recovery_label: None
        mass_bins: 4 # Mass bins. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        redshift_bins: 10 # Redshift bins. Can be number of bins, or (xmin, xmax, dx).
        mass_lim: None # Mass limits in plots. Must be 2 numbers (min, max) or None.
        redshift_lim: None # Redshift limits in plots. Must be 2 numbers (min, max) or None.
        recovery_lim: None # Recovery rate limits in plots. Must be 2 numbers (min, max) or None.

        masks: # Mask objects used in the computation of recovery rates.
            case: Unmatched # Which clusters to mask on recovery rate computations. Options: None, All, Unmatched.
            in_footprint1: # Flag if cluster is inside footprint.
                name: self # Name for column.
                use: True # Use this mask.
            in_footprint2: # Flag if cluster is inside footprint.
                name: other # Name for column. It will receive a ft_ prefix.
                use: True # Use this mask.
            coverfraction: # Many coverfractions can be computed by adding more "coverfraction" sections with any suffixes.
                name: other_1arcsec # Name for coverfraction column. It will receive a cf_ prefix.
                min: 0.1 # Minimum value of cover fraction to be considered.

mt_metrics_distances: # Distances between matched pairs.

    figsize: 20 20 # Figure size of figures in cm.
    dpi: 150 # The resolution in dots per inch.
    plot_case: simple panel 2D # Types of plots to be done. Options are simple, panel, 2D or all.
    matching_type: cross # options are cross, cat1, cat2.
    line_type: steps # line, steps.
    radial_bins: 20 # bins for radial distances. Can be number of bins, or (xmin, xmax, dx).
    radial_bin_units: arcmin # units of radial bins.
    delta_redshift_bins: 20 # bins for redshift distances. Can be number of bins, or (xmin, xmax, dx).
    add_mass_label: True # Add labels and legends of mass bins.
    add_redshift_label: True # Add labels and legends of redshift bins.

    catalog1:
        log_mass: True
        mass_num_fmt: .2f # Format the values of mass binedges (ex: '.2f') in label.
        redshift_num_fmt: .1f # Format the values of redshift binedges (ex: '.2f') in label.
        mass_bins: 4 # Mass bins. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        redshift_bins: 10 # Redshift bins. Can be number of bins, or (xmin, xmax, dx).

    catalog2:
        log_mass: True
        mass_num_fmt: .2f # Format the values of mass binedges (ex: '.2f') in label.
        redshift_num_fmt: .1f # Format the values of redshift binedges (ex: '.2f') in label.
        mass_bins: 4 # Mass bins. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        redshift_bins: 10 # Redshift bins. Can be number of bins, or (xmin, xmax, dx).

mt_metrics_mass: # Scaling relation.

    figsize: 20 20 # Figure size of figures in cm.
    dpi: 150 # The resolution in dots per inch.
    plot_case: all # Types of plots to be done. Options are zcolors, density, density_panel, distribution, self_distribution, density_dist.
    matching_type: cross # options are cross, cat1, cat2.
    add_redshift_label: True # Add redshift label in panels.
    add_err: True # Plot errorbars when available.
    add_cb: True # Add color bar in color plots.
    log_mass: True # Mass in log scale.
    ax_rotation: 0 # For density plots. Angle (in degrees) for rotation of axis of binning. Overwrites use of mass_bins in catalogs.
    rotation_resolution: 30 # For density plots. Number of bins to be used when ax_rotation!=0.

    add_bindata: False # Plot binned data to be used for fit.
    add_fit: False # Fit and plot binned dat.
    add_fit_err: True # Use error of component y in fit.
    fit_statistics: mode # Statistics to be used in fit. Options are: individual, mode, mean

    catalog1:
        redshift_bins: 5 # Redshift bins for panels. Can be number of bins, or (xmin, xmax, dx).
        redshift_num_fmt: .2f # Format the values of redshift binedges (ex: '.2f') in label.
        mass_bins: 4 # Mass bins for density colors. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        mass_bins_dist: 30 # Mass bins for distribution histograms. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        mass_num_fmt: .1f # Format the values of mass binedges (ex: '.2f') in label (10^mass_num_fmt is used if log_mass).
        fit_mass_bins: 5 # Bins to compute statistics for fit.
        fit_mass_bins_dist: 20 # Bins to compute distribution of catalog2 mass.

    catalog2:
        redshift_bins: 5 # Redshift bins for panels. Can be number of bins, or (xmin, xmax, dx).
        redshift_num_fmt: .2f # Format the values of redshift binedges (ex: '.2f') in label.
        mass_bins: 4 # Mass bins for density colors. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        mass_bins_dist: 30 # Mass bins for distribution histograms. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        mass_num_fmt: .1f # Format the values of mass binedges (ex: '.2f') in label (10^mass_num_fmt is used if log_mass).
        fit_mass_bins: 5 # Bins to compute statistics for fit.
        fit_mass_bins_dist: 20 # Bins to compute distribution of catalog1 mass.

mt_metrics_redshift: # Scaling relation.

    figsize: 20 20 # Figure size of figures in cm.
    dpi: 150 # The resolution in dots per inch.
    plot_case: all # Types of plots to be done. Options are masscolors, density, density_panel, distribution, self_distribution, density_dist.
    matching_type: cross # options are cross, cat1, cat2.
    add_mass_label: True # Add mass label in panels.
    add_err: True # Plot errorbars when available.
    add_cb: True # Add color bar in color plots.
    log_mass: True # Mass in log scale.
    ax_rotation: 0 # For density plots. Angle (in degrees) for rotation of axis of binning. Overwrites use of redshifts_bins in catalogs.
    rotation_resolution: 30 # For density plots. Number of bins to be used when ax_rotation!=0.

    add_bindata: False # Plot binned data to be used for fit.
    add_fit: False # Fit and plot binned dat.
    add_fit_err: True # Use error of component y in fit.
    fit_statistics: mode # Statistics to be used in fit. Options are: individual, mode, mean

    catalog1:
        mass_bins: 4 # Mass bins for density colors. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        mass_num_fmt: .1f # Format the values of mass binedges (ex: '.2f') in label.
        redshift_bins: 10 # Redshift bins for panels. Can be number of bins, or (xmin, xmax, dx).
        redshift_bins_dist: 30 # Redshift bins for distribution histograms. Can be number of bins, or (xmin, xmax, dx).
        redshift_num_fmt: .1f # Format the values of redshift binedges (ex: '.2f') in label.
        fit_redshift_bins: 5 # Bins to compute statistics for fit.
        fit_redshift_bins_dist: 20 # Bins to compute distribution of catalog2 redshift.

    catalog2:
        mass_bins: 4 # Mass bins for density colors. Can be number of bins, or (xmin, xmax, dx). If log_mass provide log of values.
        mass_num_fmt: .1f # Format the values of mass binedges (ex: '.2f') in label.
        redshift_bins: 10 # Redshift bins for panels. Can be number of bins, or (xmin, xmax, dx).
        redshift_bins_dist: 30 # Redshift bins for distribution histograms. Can be number of bins, or (xmin, xmax, dx).
        redshift_num_fmt: .1f # Format the values of redshift binedges (ex: '.2f') in label.
        fit_redshift_bins: 5 # Bins to compute statistics for fit.
        fit_redshift_bins_dist: 20 # Bins to compute distribution of catalog1 redshift.
