name: Build and Check

on:
  push:
    branches:
      - main
  pull_request:

env:
  CONDA_ENV_NAME: clevar


jobs:


  code-vers-valid:
    name: Version Validation
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI on current branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_branch="${GITHUB_REF_NAME}"
          echo "Triggering check_version.yml on current branch: $current_branch"
          gh workflow run check_version.yml \
            -f branch="$current_branch"


  format-valid:
    name: Format validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code formatting with black
        run: |
          pip install black black-configparser
          black --check --diff clevar tests
      - name: Check import order with isort
        run: |
          pip install isort
          isort --check --diff clevar tests
      - name: Analysing the code with pylint
        run: |
          #pip install swig sphinx sphinx_rtd_theme nbconvert pandoc ipython
          pip install pylint
          pylint clevar --ignored-classes=astropy.units


  doc-valid:
    name: Documentation Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          environment-file: environment.yml
      - uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/pkgs
          key: ${{ runner.os }}-conda-${{ env.CONDA_ENV_NAME }}
      - name: Install the package
        shell: bash -l {0}
        run: pip install .
      - name: Run the docs
        shell: bash -l {0}
        run: make -C docs/ html


  main-valid:
    name: Code Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          environment-file: environment.yml
      - uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/pkgs
          key: ${{ runner.os }}-conda-${{ env.CONDA_ENV_NAME }}
      - name: Install the package
        shell: bash -l {0}
        run: pip install .
      - name: Run the unit tests
        shell: bash -l {0}
        run: pytest tests/ --cov=clevar/
        env:
          DISPLAY: test
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls
          coveralls --service=github
